apiVersion: apps/v1
kind: Deployment
metadata:
  name: room-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: room-service
  template:
    metadata:
      labels:
        app: room-service
    spec:
      containers:
        - name: room-service
          image: asia-south1-docker.pkg.dev/sunilproject-486218/hotel-repo/room-service:v10
          # image: asia-south1-docker.pkg.dev/sunilproject-486218/hotel-repo/room-service:v8
          ports:
            - containerPort: 8087
